import { useState } from 'react';
import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Checkbox, IconButton, Menu, MenuItem, ListItemIcon } from '@mui/material';
import { MoreVert, Inventory2Outlined } from '@mui/icons-material';
import type { Alert, AlertActivityAction, Asset } from '../../data/types';
import { formatRelativeTime } from '../../utils/relativeTime';
import { CATEGORY_STYLE, formatReviewerName } from '../../utils/alertReview';
import { LIFECYCLE_STEP_LABELS, getModelType } from '../../utils/alertFilters';
import { AlertThumbnail, ReviewRow, lastActorFor } from './AlertsKanbanBoard';

const HEADER_CELL_SX = {
  fontSize: 12, fontWeight: 500, fontFamily: 'Roboto, sans-serif',
  color: '#686576', letterSpacing: '0.17px', borderBottom: '1px solid #f0f0f0', whiteSpace: 'nowrap',
} as const;

const BODY_CELL_SX = {
  fontSize: 12, fontFamily: 'Roboto, sans-serif', color: '#1f1d25', verticalAlign: 'top',
} as const;

const ACTIVITY_VERB: Record<AlertActivityAction, string> = {
  generated: 'Generated by',
  email_approved: 'Email approved by',
  email_rejected: 'Email rejected by',
  assets_approved: 'Assets approved by',
  assets_rejected: 'Assets rejected by',
  rebuilt: 'Rebuilt by',
  sent: 'Sent by',
  archived: 'Archived by',
};

/** The most recent activity entry across both tracks, shown as the row's "Last Update" summary. */
function formatLastUpdate(alert: Alert): { line: string; time: string } | null {
  const last = alert.activity[alert.activity.length - 1];
  if (!last) return null;
  const actor = last.action === 'generated' ? last.actorName : formatReviewerName(last.actorName);
  return { line: `${ACTIVITY_VERB[last.action]} ${actor}`, time: formatRelativeTime(last.timestamp) };
}

interface AlertsTableProps {
  alerts: Alert[];
  assetsByAlertId: Map<string, Asset[]>;
  onOpenAlert: (id: string) => void;
  /** Manual archive action — omitted for the read-only Archived Alerts dialog's own table view. */
  onArchive?: (id: string) => void;
}

export const AlertsTable = ({ alerts, assetsByAlertId, onOpenAlert, onArchive }: AlertsTableProps) => {
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [menuState, setMenuState] = useState<{ id: string; el: HTMLElement } | null>(null);

  const allSelected = alerts.length > 0 && alerts.every((a) => selectedIds.has(a.id));
  const someSelected = alerts.some((a) => selectedIds.has(a.id));

  const toggleAll = () => {
    setSelectedIds(allSelected ? new Set() : new Set(alerts.map((a) => a.id)));
  };

  const toggleRow = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  return (
    <TableContainer style={{ flex: 1, minHeight: 0 }}>
      <Table stickyHeader size="small">
        <TableHead>
          <TableRow>
            <TableCell padding="checkbox" sx={{ borderBottom: '1px solid #f0f0f0', background: '#ffffff' }}>
              <Checkbox
                size="small"
                checked={allSelected}
                indeterminate={someSelected && !allSelected}
                onChange={toggleAll}
                sx={{ color: '#9c99a9', '&.Mui-checked': { color: '#473bab' } }}
              />
            </TableCell>
            <TableCell sx={{ ...HEADER_CELL_SX, background: '#ffffff' }} />
            <TableCell sx={{ ...HEADER_CELL_SX, background: '#ffffff' }}>Alert Subject</TableCell>
            <TableCell sx={{ ...HEADER_CELL_SX, background: '#ffffff' }}>Lifecycle Status</TableCell>
            <TableCell sx={{ ...HEADER_CELL_SX, background: '#ffffff' }}>Category</TableCell>
            <TableCell sx={{ ...HEADER_CELL_SX, background: '#ffffff' }}>Model Type</TableCell>
            <TableCell sx={{ ...HEADER_CELL_SX, background: '#ffffff' }}>Approvals</TableCell>
            <TableCell sx={{ ...HEADER_CELL_SX, background: '#ffffff' }}>Last Update</TableCell>
            {onArchive && <TableCell sx={{ ...HEADER_CELL_SX, background: '#ffffff' }} />}
          </TableRow>
        </TableHead>
        <TableBody>
          {alerts.map((alert) => {
            const isSelected = selectedIds.has(alert.id);
            const categoryStyle = CATEGORY_STYLE[alert.category];
            const lastUpdate = formatLastUpdate(alert);

            return (
              <TableRow
                key={alert.id}
                hover
                onClick={() => onOpenAlert(alert.id)}
                sx={{
                  cursor: 'pointer', background: isSelected ? 'rgba(99,86,225,0.08)' : 'transparent',
                  '& td': { borderBottom: '1px solid #f0f0f0' },
                  '&:hover .row-archive-btn': { opacity: 1 },
                }}
              >
                <TableCell padding="checkbox" onClick={(e) => e.stopPropagation()}>
                  <Checkbox
                    size="small"
                    checked={isSelected}
                    onChange={() => toggleRow(alert.id)}
                    sx={{ color: '#9c99a9', '&.Mui-checked': { color: '#473bab' } }}
                  />
                </TableCell>
                <TableCell sx={BODY_CELL_SX}>
                  <AlertThumbnail assets={assetsByAlertId.get(alert.id) ?? []} size={40} />
                </TableCell>
                <TableCell sx={{ ...BODY_CELL_SX, maxWidth: 280 }}>
                  <span style={{ display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden', lineHeight: 1.43 }}>
                    {alert.subject}
                  </span>
                </TableCell>
                <TableCell sx={BODY_CELL_SX}>
                  <span style={{ display: 'inline-flex', alignItems: 'center', background: '#f0f2f4', color: '#1f1d25', borderRadius: 8, padding: '2px 8px', fontSize: 11, letterSpacing: '0.4px', whiteSpace: 'nowrap' }}>
                    {LIFECYCLE_STEP_LABELS[alert.status]}
                  </span>
                </TableCell>
                <TableCell sx={BODY_CELL_SX}>
                  <span style={{ display: 'inline-flex', alignItems: 'center', background: categoryStyle.background, color: categoryStyle.color, borderRadius: 8, padding: '2px 8px', fontSize: 11, letterSpacing: '0.4px', whiteSpace: 'nowrap' }}>
                    {alert.category}
                  </span>
                </TableCell>
                <TableCell sx={BODY_CELL_SX}>
                  <span style={{ display: 'inline-flex', alignItems: 'center', background: '#f0f2f4', color: '#1f1d25', borderRadius: 8, padding: '2px 8px', fontSize: 11, letterSpacing: '0.4px', whiteSpace: 'nowrap' }}>
                    {getModelType(alert)}
                  </span>
                </TableCell>
                <TableCell sx={{ ...BODY_CELL_SX, minWidth: 200 }}>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                    <ReviewRow label="Email content" status={alert.emailStatus} actorName={lastActorFor(alert, 'email')} revealActor />
                    <ReviewRow label="Assets" status={alert.assetsStatus} actorName={lastActorFor(alert, 'assets')} revealActor />
                  </div>
                </TableCell>
                <TableCell sx={{ ...BODY_CELL_SX, whiteSpace: 'nowrap' }}>
                  {lastUpdate && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                      <span>{lastUpdate.line}</span>
                      <span style={{ color: '#9c99a9', fontSize: 11, letterSpacing: '0.4px' }}>{lastUpdate.time}</span>
                    </div>
                  )}
                </TableCell>
                {onArchive && (
                  <TableCell padding="none" onClick={(e) => e.stopPropagation()} sx={{ width: 40 }}>
                    <IconButton
                      className="row-archive-btn"
                      size="small"
                      onClick={(e) => setMenuState({ id: alert.id, el: e.currentTarget })}
                      sx={{ opacity: 0, padding: '4px', transition: 'opacity 0.1s' }}
                    >
                      <MoreVert style={{ fontSize: 18, color: '#686576' }} />
                    </IconButton>
                  </TableCell>
                )}
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
      {onArchive && (
        <Menu anchorEl={menuState?.el ?? null} open={!!menuState} onClose={() => setMenuState(null)}>
          <MenuItem
            onClick={() => {
              if (menuState) onArchive(menuState.id);
              setMenuState(null);
            }}
          >
            <ListItemIcon><Inventory2Outlined fontSize="small" /></ListItemIcon>
            Archive Alert
          </MenuItem>
        </Menu>
      )}
    </TableContainer>
  );
};
